version: "3.9"

services:
  app:
    env_file:
      - ./.env  # .env 파일 경로
    build:
      context: .
      dockerfile: Dockerfile
    image: order-service
    container_name: order-service-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
